### ISSUE TITLE
Edge case when user has bought food orders outside of India

### ISSUE THREAD

**Issue by mohanrohith** [harshnitk17/zomato-spending-calculator#4]
When a user has used his account outside India, `totalCost` is denoted in corresponding currency shown as attached.
<img width="181" alt="Screenshot 2022-10-13 at 12 13 20 AM" src="https://user-images.githubusercontent.com/310622/195439955-bebdb286-40a3-4819-8868-1ed9d5db0371.png">

In this scenario, cost is shown as `NaN`. You need to include currency check for this edgecase.

**Comment by hpgupt** [comment]
Thanks for pointing out this edge case

**Comment by hpgupt** [comment]
Hi @mohanrohith ,  I have tried to include a fix for this issue in v1.1.5 , can you check if the issue has been fixed or not.

**Comment by mohanrohith** [comment]
Yes. That fixes the issue. 
But the total shows a different amount that I derive from my scripts. Will crosscheck. Anyways lets close this issue.
